"""added relationship tables

Revision ID: 5787ff26113c
Revises: 08f7ef9c736c
Create Date: 2023-10-07 19:03:30.679622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5787ff26113c'
down_revision = '08f7ef9c736c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_job', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_job', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
