"""join table to link job and employee

Revision ID: d3ca6bcaab40
Revises: de69ad95ad3a
Create Date: 2023-10-10 12:40:32.304714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ca6bcaab40'
down_revision = 'de69ad95ad3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])
        batch_op.drop_column('job')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
